on:
    pull_request:
        branches:
            - master
        types: [opened, labeled]

name: check lint or do lint

jobs:
    check-lint:
        name: lint
        runs-on: ubuntu-latest
        if: github.event.action == 'opened' || (github.event.action == 'labeled' && github.event.label.name == 'run-fmt')
        steps: 
            - name: checkout
              uses: actions/checkout@v4      
              with:
                  fetch-depth: 0
                  ref: ${{github.event.pull_request.head.ref}}
                  repository: ${{github.event.pull_request.head.repo.full_name}}
            - name: install dependencies
              run: npm install
            - name: lint
              run: npm run fix
            - name: check diff
              id: check-diff
              run: |
                set +e
                git diff --exit-code
                exitcode="$?"
                echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
            - if: steps.check-diff.outputs.exitcode == 0
              name: comment
              env: 
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                gh pr comment ${{ github.event.pull_request.number }} --body ":tada: Lint passed!"
            - if: steps.check-diff.outputs.exitcode != 0 && (github.event.action == 'labeled' && github.event.label.name == 'run-fmt')
              name: push on labeled run
              env: 
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git status
                  git config --global user.email "github-actions@github.com"
                  git config --global user.name "github-actions"
                  git add .
                  git commit -m "lint"
                  git push
            - if: steps.check-diff.outputs.exitcode != 0
              name: comment
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh pr comment ${{ github.event.pull_request.number }} --body ":white_check_mark: Lint fixed"
