on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

name: Edit commnet to match merging commits

jobs:
  edit-comment:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/github-script@v7
      name: get-pull-description
      id: get-pull-description
      with:
        script: |
          const pullp = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          }
          const { data: pull } = await github.rest.pulls.get(pullp)
          core.setOutput('description', pull.body)

    - if: github.event.action == 'opened'
      uses: actions/github-script@v7
      env:
        description: ${{ steps.get-pull-description.outputs.description }}
      with:
        script: |
          const pullp = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          }
          const description = process.env.description
          const { data: commits } = await github.rest.pulls.listCommits(pullp)
          console.log("commits", commits)
          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            body: description + '\n' + commits.map(c => c.commit.message).join('\n'),
          }
          github.rest.pulls.update(params)
  
    - if: github.event.action == 'synchronize'
      uses: actions/github-script@v7
      env:
        description: ${{ steps.get-pull-description.outputs.description }}
      with:
        script: |
          const pullp = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          }
          const description = process.env.description
          const { data: commits } = await github.rest.pulls.listCommits(pullp)
          const filterdCommits = []
          let adding = false
          for (const commit of commits) {
            if (adding) {
              filterdCommits.push(commit)
            }
            if (commit.sha === context.payload.before) {
              adding = true
            }
          }
          console.log("commits", filterdCommits)
          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            body: description + '\n' + filterdCommits.map(c => c.commit.message).join('\n'),
          }
          github.rest.pulls.update(params)