# Run secret-dependent integration tests only after /deploy approval
on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

name: Edit commnet to match merging commits

jobs:
  # Repo owner has commented /deploy on a (fork-based) pull request
  edit-comment:
    runs-on: ubuntu-latest
    steps:
    - name: 'PR commits + 1'
      id: pr-commit
      run: echo "PR_FETCH_DEPTH=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "${GITHUB_OUTPUT}"
    - uses: actions/checkout@v4
      id: checkout
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: ${{ steps.pr-commit.outputs.PR_FETCH_DEPTH }}
    - uses: actions/github-script@v7
      env:
      #   check_id: ${{ steps.checkout.outputs }}
      #   details_url: ${{ github.server_url }}/${{ github.repository }}/runs/${{ github.run_id }}
        commits: ${{ github.event.commits }}
      with:
        script: |
          console.log(process.env.commits)
          const params = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            body: 'This is a test comment'
          }
          github.rest.pulls.update(params)
          const p2 = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          }
          console.log("pr",  github.rest.pull_request)
          // const resp = await github.rest.pulls.commits(params)
          // console.log(resp)